### ISSUE TITLE
Energy and angular momentum conservation in Phantom

### ISSUE THREAD

**Issue by LayaGhodsi** [danieljprice/phantom#101]
Hi,
I've run a simulation of an isolated galaxy using Phantom, but surprisingly the energy and the angular momentum of the system are not conserved! The simulation setup (phantom/build/Makefile) is as follows:

"ifeq ($(SETUP), galdisc)
    IND_TIMESTEPS=yes
    H2CHEM=no
    ISOTHERMAL=no
    GRAVITY=yes
    MHD=no
    SETUPFILE= setup_galdisc.f90
    KNOWN_SETUP=yes
endif"

The Phantom input file is attached:
[PHANTOM_galdisc.pdf](https://github.com/danieljprice/phantom/files/5688058/PHANTOM_galdisc.pdf)

The initial conditions are generated using [DICE](https://bitbucket.org/vperret/dice/wiki/Running%20DICE) with the following input file:
[DICE_isolated_galaxy.pdf](https://github.com/danieljprice/phantom/files/5688060/DICE_isolated_galaxy.pdf)

And these plots show the evolution of the galaxy's energy and angular momentum magnitude:
![1-EnergyConservation](https://user-images.githubusercontent.com/47304124/102068769-1d7d0c80-3e12-11eb-8356-5c553d323e97.png)
![1-AngMomentumConservation](https://user-images.githubusercontent.com/47304124/102068759-18b85880-3e12-11eb-8832-eca91e9599b5.png)
The left panels show the evolution of the mentioned parameters vs time, and the right panels show the evolution of the relative difference of them vs time.
I can't figure out what is the cause of this problem. I'll greatly appreciate any comments on this issue.

Thanks,
Laya

**Comment by jameswurster** [comment]
Near the beginning of the output file, it lists what the initial energies are in code units.  What are these values?  If they are too large or too small, it can lead to lack of conservation (I have previously seen this in cluster evolution and colliding galaxies). You want these values to be on order 1 (or 10); this can be achieved by picking more appropriate code units.

**Comment by LayaGhodsi** [comment]
Thank you for your response! 
This is the top of my "galdisk.ev" file:
![Screenshot from 2020-12-14 16-18-54](https://user-images.githubusercontent.com/47304124/102084683-c2a3df00-3e2a-11eb-9f77-88f4a15c411b.png)
It looks that all types of energy are too larger than 1 in code units. So can I solve the problem by just changing the code units? What about the angular momentum?

**Comment by jameswurster** [comment]
You can only self-consistently change the mass and distance units.  Modify these to decrease your energy in code units, and that should also take care of the large angular momentum
A good starting point would be to set the mass unit to be on order of the total mass of your system, and the length unit to be on order of the size of your galaxy.

**Comment by LayaGhodsi** [comment]
I have changed the mass unit and the distance unit in the way you mentioned and run the simulation for a short time. This is the output file:
![Screenshot from 2020-12-15 00-09-50](https://user-images.githubusercontent.com/47304124/102133652-ad4ea500-3e6a-11eb-95ee-f537f07ab0a2.png)
Now, all types of energy are in order 1 or 10 except etherm and unfortunately, the conservation problem still remains. Besides, I guess "angtot" should be the total angular momentum magnitude of the system. If I'm right, this variable is also too small. How can I fix these as well?
Do I have to keep G=1 in my simulation? Can it be the cause of this problem?

**Comment by jameswurster** [comment]
The code values will make the calculation much happier.
If you are using G, then the time code unit is automatically set using G==1 (assuming you set the mass and distance unit).  If gravity is on, then Phantom will not let you violate this.
Since you are including an external force, I'm not convinced that energy should be conserved... When using an external force, we no longer force momentum or angular momentum to be conserved.  
Try letting your code run and see what happens.  If Phantom is exiting due to lack of energy conservation, the you can override it with the environment variable I_WILL_NOT_PUBLISH_CRAP=yes.
Given what you are simulating, I would recommend contacting Alex Pettitt who runs similar simulations with Phantom, so has more experience with your setup.
Good luck.

**Comment by LayaGhodsi** [comment]
Sure, I'll run the simulation for a longer time to see what happens and talk to professor Pettitt.
Thank you so much for your help.
Best regards,
Laya

**Comment by arptttt** [comment]
Chiming in! We corrected the angular momentum issue by flipping idisk=0, as it was causing a "doubling up" of gravity for this IC. Still looking at energy...

**Comment by danieljprice** [comment]
am closing as from @jameswurster I believe this is resolved?
