### ISSUE TITLE
unable to checkout a stable release

### ISSUE THREAD

**Issue by palvib** [danieljprice/phantom#127]
Hello, 

I am new to Phantom. I was trying to get it running on my system/cluster here. 
I followed the instructions on bitbucket documentation. I did the following : 

git clone https://github.com/danieljprice/phantom
cd phantom
git checkout stable

I get the following : error: pathspec 'stable' did not match any file(s) known to git.

Anyway, I tried to compile the code on two different systems, one with fortran and the other with ifort 
and with both - make test - failed at seemingly the same point. With the gfortran, I got the following error: 

------------
gfortran -c -O3 -Wall -Wno-unused-dummy-argument -frecord-marker=4 -gdwarf-2 -finline-functions-called-once -finline-limit=1500 -funroll-loops -ftree-vectorize -std=f2008 -fall-intrinsics -mcmodel=medium -fPIC -fopenmp -fdefault-real-8 -fdefault-double-8  -DPERIODIC -DMHD -DDUST -DCONST_ARTRES -DCURLV -DRADIATION ../src/main/eos.F90 -o eos.o
../src/main/eos.F90:390.79:

   call fatal('eos','invoking KROME to calculate local gamma but variable '&
                                                                           1
Error: Syntax error in argument list at (1)
make[2]: *** [eos.o] Error 1
------------

Can I please get some help on this? 

Best,
Pallavi

**Comment by jameswurster** [comment]
Hello and welcome to Phantom!

The documentation regarding the stable branch is out of date.  We no longer have a stable branch, and the current version on the repo should just work since it any changes must pass several tests before being merged to the main repo.  (@danieljprice , we need to update the stable branch documentation since it still references bitbucket.)

Regarding your error, can you please let me know what version of gfortran you are using?  I just successfully ran make test on my local machine without any issues. 

Cheers

**Comment by palvib** [comment]
Thanks for the welcome! 

Well, I checked the version of fortran and it is indeed an older one : 
GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.

I tried to install my own copy of gcc-gfortran on my account on the cluster 
but the installation (make) never seems to reach an end point. I will try again. 

I am wondering about certain things. I have previously used grid-based codes which are MPI 
compatible. So can Phantom also work with MPI? 
Then would it compile with mpif90, mpicc? If so, how can one do that?  

Cheers
Pallavi

**Comment by jameswurster** [comment]
My computer and clusters are using newer versions of gfortran.  I'm not sure why that would make a difference.  In src/main/eos.F90, replace the two lines
       call fatal('eos','invoking KROME to calculate local gamma but variable '&
                        'not passed in equationofstate (bad value for eos?)')
with
       call fatal('eos','invoking KROME to calculate local gamma but variable not passed in equationofstate (bad ieos?)')
and see if that works.  

Phantom can run with MPI, but I would suggest getting comfortable with the openmp version first.  If you do want to try mpi, compile as (e.g.) 
make SYSTEM=gfortran MPI=yes
and run as (e.g.) 
mpiexec -np 2 ./phantom mysim.in

Good luck

**Comment by palvib** [comment]
Thanks!

So just a while ago, my gcc-gfortran build got completed (it takes 4 hours or so, phew). 
And turns out that the test suite runs fine with the new version of gfortran : 
SUMMARY OF ALL TESTS:
PASSED: 154 of 154 100.0%
FAILED:   0 of 154   0.0%

 ____   _    ____ ____  
|  _ \ / \  / ___/ ___| 
| |_) / _ \ \___ \___ \ 
|  __/ ___ \ ___) |__) |
|_| /_/   \_\____/____/ 

TEST SUITE PASSED

I will now next look at the examples in the documentation and try to understand the usage of the code. 
Then I will try with MPI. My aim is to run an MHD turbulence simulation eventually (which I have previously run 
on grid-based codes).  

Thanks again for your help!

Best,
Pallavi

**Comment by jameswurster** [comment]
Glad that you got Phantom running.
Feel free to close this issue.  
We are here to help as other issues arise.
Cheers
