### ISSUE TITLE
Error while converting standard output files to HDF5 format

### ISSUE THREAD

**Issue by auratrik** [danieljprice/phantom#137]
Hello, 
I am new to Phantom. I have managed to successfully run the simulation. The output files I got after running the simulation are the standard output files. However, I need them in the hdf5 format.

I followed the instructions on the bitbucket documentation for converting to the hdf5 format using the phantom2hdf5 utility. 
I managed to successfully install the hdf5 package (version: 1.12.1) at the location: HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial

I used these parameters:
export CC=gcc
export F9X=gfortran
export CXX=g++

Then I followed these steps:

make HDF5=yes HDF5ROOT=$HDF5_DIR

export LD_LIBRARY_PATH=/usr/local/hdf5/lib:$LD_LIBRARY_PATH

Then in the simulation directory:
make SYSTEM=gfortran HDF5=yes PHANTOM2HDF5=yes HDF5ROOT=/usr/lib/x86_64-linux-gnu/hdf5/serial phantom2hdf5

After following these steps the following error is occuring while compiling for the phantom2hdf5 utility:

../src/main/utils_dumpfiles_hdf5.f90:975:10:

  975 |  if (got) got_arrays%got_orig = .true
      |          1
Error: Cannot assign to a named constant at (1)
make[2]: *** [Makefile:1711: utils_dumpfiles_hdf5.o] Error 1
make[2]: Leaving directory '/home/auratrik/phantom-master/build'
make[1]: *** [Makefile:17: phantom2hdf5] Error 2
make[1]: Leaving directory '/home/auratrik/phantom-master'

Can I please get some help on this?

Cheers
Auratrik

**Comment by danieljprice** [comment]
Dear Auratrik,
 
 Thanks for flagging this. Support for hdf5 is problematic in several respects, and not something I have a lot of time for. There are untouched existing issues flagged regarding phantom2hdf5 (#46), so I'm not surprised you're encountering problems here. Support for hdf5 relies on the willingness of users to fix the problems with it.
 
The only officially supported output format in phantom is the native binary output, which can be converted to other formats using splash, or using the various python readers. The hdf5 routines unfortunately copy a lot of code from the main routines, so it is hard to maintain both in a useable state. Again, user contributions here are welcomed if this is a desired feature.

Cheers,

Daniel

**Comment by auratrik** [comment]
Hi Daniel,
Thanks for your help. I may attempt to fix the hdf5 issue at a later point, but now as I am just learning the stuff so, I might let it pass. I shall instead focus on using the python readers.

Cheers,
Auratrik

**Comment by chanconrad** [comment]
Hi @auratrik,

I've fixed this problem in #160. Feel free to give it another try. There were some trivial typos (missing a `.` from `.true.`) that were not caught because some changes in c21cf7c2fb281dfea67c7e929985d3b1102b2df6 were not build tested prior to pushing.

**Comment by auratrik** [comment]
Hi @chanconrad 

Thanks!
I was able to fix the bugs in the code and the code ran perfectly.

Cheers 
Auratrik
