### ISSUE TITLE
read_phantom_arrays() does not work with MPI and boundary particle types

### ISSUE THREAD

**Issue by chanconrad** [danieljprice/phantom#150]
`SETUP=srshock`
`MPI=yes`

`./phantomsetup` with default options, except for resolution=100

```mpirun -np 2 ./phantom shock.in```

Error:
```ERROR! read_dump: particle type counts do not match header```

Runs OK with `-np 1`.

This is caused by iphase not being read correctly.

The subroutine `read_array_int1` is used to read iphase from the output file. On task `id==1`,  `noffset=34368`, so that it reads the second half of the particles, but iphase never gets touched. 

Possibly caused by the boundary particle types, because `MPI=yes` with 2 tasks runs OK with the `polar` and `grtde` setup.

I'm unfamiliar with the proprietary binary file, so I'm unable to continue tracking this down.

**Comment by dliptai** [comment]
Additionally, I noticed that `read_array()` returns `ierr=5016` when reading iphase on the second task
