### ISSUE TITLE
Old output files are incompatible

### ISSUE THREAD

**Issue by conradtchan** [danieljprice/phantom#151]
The binary file format changes over time, but phantom does not check for compatibility when reading old files.

In 0ee3d8da8d8756cd29e6969b341a16d24ee4752b, `maxtypes` is increased by 1, so that output files have 8 types instead of 7.

When reading old files, this results in junk/NaN values in the 8th particle type. This causes the code to crash when using `DEBUG=yes`. This is a problem for the benchmark suite (https://github.com/phantomSPH/phantom-benchmarks) because the initial conditions were generated before this change.

Proposed fix: log file format version numbers in the file header and throw a warning to alert the user that an old file is being read. Attempt to recover the run. Most of the time, this should be easy, e.g. in this case just set the values for the 8th particle type to zero.

**Comment by danieljprice** [comment]
thanks for flagging. 

we do already have a version number in the file headers, but this is only when the actual format changes in a manner which is backwards *incompatible*. In this case the format itself is not changed at all -- maxtypes is just a number in the metadata in the header. We have not changed the way the header itself is written or read.

Better would be to just fix the backwards compatibility problem, i.e. deal with the situation where maxtypes in the code exceeds the number of types read from the file (which could happen a lot, maxtypes can change arbitrarily depending on a compile time flag giving the maximum number of dust species).  This would be an issue irrespective of the file format.

**Comment by danieljprice** [comment]
this error is fixed
