### ISSUE TITLE
(relax_star) step_extern: dt <= 0 in sink-gas substepping

### ISSUE THREAD

**Issue by themikelau** [danieljprice/phantom#16]
Error message:
` FATAL ERROR! step_extern: dt <= 0 in sink-gas substepping : dt =  0.000E+00`

Steps to reproduce:
Run phantomsetup (SETUP=star) on the attached .setup file in a directory containing the stellar profiles mysoftenedstar2.dat and profileCHeB2.data

[files.zip](https://github.com/danieljprice/phantom/files/4811247/files.zip)

**Comment by danieljprice** [comment]
I can reproduce this

**Comment by danieljprice** [comment]
this is now fixed
