### ISSUE TITLE
Branch protection rules

### ISSUE THREAD

**Issue by conradtchan** [danieljprice/phantom#226]
#224 changes the build workflow name from the format "build (SYSTEM=gfortran)" to "build (batch 1, SYSTEM=gfortran)" due to parallelisation.

The branch protection rules still looks for the old format which no longer exists, so PRs will never be allowed to merge.

One solution is to add all N batch names to the protection rules, but this is cumbersome, and will break in the build parallelism changes.

Alternatively, a job depending on all N batches can be added. If this job has the same name as the old format, then no change from the repo owner is required.

**Comment by danieljprice** [comment]
really we want to just say that all actions must pass before merge, rather than enforcing only certain workflows

**Comment by danieljprice** [comment]
apparently this is not possible: https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957

**Comment by danieljprice** [comment]
I think this is now done, "build" is now required. Probably would be good if we could indicate "test" and "mpi" as well instead of having to list the tests individually...
