### ISSUE TITLE
Actions: Use Intel OneAPI compiler to avoid needing custom runners

### ISSUE THREAD

**Issue by conradtchan** [danieljprice/phantom#227]
As mentioned in #224, the build with `SYSTEM=ifort` is slow, even with parallelised builds, because there are only 4 custom runners. The maximum speedup from parallelisation is 4x, and during busy times there is a long backlog. This slows down the development workflow.

Intel's compilers are now free for academic use. 

Instructions for using ifort in github actions: https://neelravi.com/post/oneapi-github-workflow/

Workflows requiring ifort can be run on github's runners (and thus on forks). The benchmarks should still be run on the custom runners because consistent system hardware and dedicated CPU cores are required for timing.

**Comment by danieljprice** [comment]
awesome :)
