### ISSUE TITLE
segfault with 8 MPI tasks and OMP_NUM_THREADS=8

### ISSUE THREAD

**Issue by dliptai** [danieljprice/phantom#260]
Code segfaults with 8 MPI tasks and 8 openMP threads per task (on OzSTAR)

- Caused by xyzcache in force and dens
- Setting the cache size to zero allowed the code to run, albeit slower

**Comment by danieljprice** [comment]
not keen on dynamic allocation of the openmp cache, threadprivate is much nicer for this...
