### ISSUE TITLE
particle ids not tracked in MPI

### ISSUE THREAD

**Issue by danieljprice** [danieljprice/phantom#27]
_Originally posted to the mailing list, basic issue is that particle IDs are not currently tracked in MPI, this needs implementing:_

I'm trying to plot the trajectory of some gas particles in my phantom simulation. If I understand the code correctly, the indices of the particles serve as the particle IDs, so I could use the index to select a certain particle at different timestep (I think splash does the same way). This works fine if I only use OPENMP parallelization. However, if I use the hybrid MPI+OPENMP parallelization, the trajectory looks quite strange (see the attached plot). I suspect the indices might have been changed while the processors communicate by MPI. I wonder whether this is a bug in Phantom, or it is a feature to accelerate the simulations with MPI enabled. 
If the indices have to be changed with MPI enabled, then I have to switch back to OPENMP, but it is known that OPENMP parallelization is not very scalable in general. For my problem: I am studying the effects of stellar bars/spirals on the galactic gaseous disk, and the bar usually drives a lot of gas into the galactic center, making a high-density ring there which cause the code runs quite slow (takes > 1 month using ~5 million particles with ISOTHERMAL, OPENMP and INDEPENDENT TIMESTEP, CPU: 32 X Intel® Xeon® Gold 6136 processor, Compiler: ifort 18).   I am not sure whether there is a better way to make the code runs faster with or without MPI (e.g. how many threads per physical core is the most optimized configuration in Phantom?).

**Comment by jameswurster** [comment]
With the kill_particle being routinely called (either if r > rkill or to remove dead particles upon restart), particle IDs will now be important for ALL runs.  
While this should be relatively simple to add to Phantom itself, it will take some time, effort and caution before it's successfully added to all the analysis routines and Splash.

**Comment by jameswurster** [comment]
This issue should be solved by commit #96
