### ISSUE TITLE
MPI, nprocs not defined 

### ISSUE THREAD

**Issue by tbdrstl** [danieljprice/phantom#326]
Hi, a great code you got there!

I am currently trying to get phantom to run, using mpi. In order to get things to work at all I had to change _mpif90_ to _mpif90.openmpi_ in `phantom/build/Makefile` like so:
```
#
# MPI flavour (mostly openmpi these days)
#
ifeq ($(MPI), yes)
    FC= mpif90.openmpi `mpif90.openmpi --showme:compile`
    CC= mpicc `mpicc --showme:compile`
    USEMPI=yes
endif
```
Only then the code compiles. However, when trying to run `./phantomsetup blah`, I get [this](https://github.com/danieljprice/phantom/files/9591855/err.txt) this error message. I tested this for the disc, turb and cluster setup and was able to replicate this behaviour on two different Linux machines. It seems like `nprocs` is not defined in `io.F90:83` if mpi is activated. This yields an floating point exception when trying to divide by it in `memory.f90:53`. Is there anything wrong with this setup? 

Thanks in advance and best regards

**Comment by danieljprice** [comment]
to run with mpi you need to run with mpiexec, e.g.

mpiexec -np 4 ./phantomsetup blah

I think this is the reason nprocs is not defined

**Comment by tbdrstl** [comment]
Thanks, that does the job!

**Comment by tbdrstl** [comment]
A follow up question: the setup changed and now I am using slurm with MPI (pure mpi was not possible). Thus changed `mpiexec` to `srun --nodelist=... --ntasks=5 --ntasks-per-node=8 ./phantomsetup blah`. The same error pops up again, just ntasks-times. Are there some parameters I am missing to specify?

**Comment by danieljprice** [comment]
I think you still need the mpiexec command after srun and before ./phantomsetup 

See example slurm script with "make qscript MPI=yes INFILE=blah.in"
