### ISSUE TITLE
Some questions about settings and processes in PHANTOM

### ISSUE THREAD

**Issue by Shigaharuki3012** [danieljprice/phantom#380]
How should I set the initial velocity of the star with respect to the central BH?I just couldn't find the velocity settings in tde.tdeparams or tde.in,which are setting files used to start calculating.
What's more, the example of TDE in official website of PHANTOM(read-the-docs) just shows the star directly falls into central BH instead of falling back again with some cross-collision process.Thus calculation will be stopped when star completely falls into the BH.I guess the velocity of the star should be modified....
The results are produced in the external utility(i.e for me,sarracen).

**Comment by danieljprice** [comment]
Yes this is a bug we found recently, it has been fixed in a pull request by Megha Sharma but the p-r is failing a few tests and has not been merged yet

**Comment by danieljprice** [comment]
just to update, this pull request has been merged so this issue should now be fixed. To clarify the velocities are given by the prescribed eccentricity for the desired TDE encounter (either eccentric e <1 or parabolic e = 1; note that hyperbolic is not yet implemented)

**Comment by Shigaharuki3012** [comment]
> just to update, this pull request has been merged so this issue should now be fixed. To clarify the velocities are given by the prescribed eccentricity for the desired TDE encounter (either eccentric e <1 or parabolic e = 1; note that hyperbolic is not yet implemented)

Thank you for your reply.So I just need to modify the eccentricity to set the initial velocity of the star with respect to the central BH instead of directly using absolete velocity we often use in daily work.
The bug having been fixed,I will try to run the program of TDE again.THank you again for your help.

**Comment by Shigaharuki3012** [comment]
I just tried the TDE simulation shown in the website again,but would always ended with "FATAL ERROR! maketree: no particles or all particles dead/accreted" ,even though I had setted "I_WILL_NOT_PUBLISH_ CRAP=yes".And the files endde with tde_00012.
So should I changed some parameters shown in the website?Because there aren't some results images after TDE simulation shown in the website ,I wonder whether the simulation is correct for me.

**Comment by Shigaharuki3012** [comment]
Just to add,the parameters are 
                  beta =       1.000    ! penetration factor
                  mh =   1.000E+06    ! mass of black hole (code units)
                  ms =       1.000    ! mass of star       (code units)
                  rs =       1.000    ! radius of star     (code units)
               theta =       0.000    ! stellar rotation with respect to x-axis (in degrees)
                 phi =       0.000    ! stellar rotation with respect to y-axis (in degrees)
                  r0 =        490.    ! starting distance
