### ISSUE TITLE
Reading parameters from tde.tdeparams does not seem to work properly

### ISSUE THREAD

**Issue by wangdi94** [danieljprice/phantom#408]
The black hole mass and the initial distance are not read correctly from tde.tdeparams. They are always the default values in tde.in even if tde.tdeparams is changed.
I found that the problem seems to be with src/utils/moddump_tidal.f90, which does not assign the black hole mass Mh read from tde.tdeparams to m0 and overwrites the initial distance r0 after reading tde.tdeparams

**Comment by msha0023** [comment]
Hi, I have fixed the code, and you should be able to assign black hole different mass from tde.tdeparams. r0 will be updated after reading tde.tdeparams. Now I have added default r0 which is set at 10*tidal radius (this is based on default radius and mass of star and SMBH). If you wish you set your stars farther/ assign the correct r0 for your BH you can just change the r0 in tde.tdeparams. Please let me know if you encounter any other issues.
