### ISSUE TITLE
Cannot checkout Phantom due to exceeding GitHub git-lfs quota

### ISSUE THREAD

**Issue by dmentipl** [danieljprice/phantom#42]
I cannot checkout Phantom due to exceeding GitHub git-lfs quota.

To reproduce:

```
git clone git@github.com:danieljprice/phantom
```

Here is the output:

```
Cloning into 'phantom'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 27519 (delta 21), reused 25 (delta 12), pack-reused 27483
Receiving objects: 100% (27519/27519), 39.50 MiB | 4.60 MiB/s, done.
Resolving deltas: 100% (21182/21182), done.
Updating files: 100% (662/662), done.
Downloading data/cooling/cooltable.dat (28 KB)
Error downloading object: data/cooling/cooltable.dat (79d3e01): Smudge error: Error downloading data/cooling/cooltable.dat (79d3e017deb76c90eb17c1f5784c31bd7947e9932fc17339f617f72df35753c0): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /Users/daniel/repos/phantom/.git/lfs/logs/20200801T104918.246695.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: data/cooling/cooltable.dat: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by danieljprice** [comment]
there appears to be both a "bandwidth" quota and a "storage" quota. Unfortunately we have no budget to pay for this unless we crowdsource funding...

**Comment by dmentipl** [comment]
One option might be to put the large files on Figshare, or a similar service, as a tarball which can be downloaded locally when required.

The git-lfs quota issue is significant. It means people simply cannot develop Phantom unless they had checked out a copy before the quota was reached.

**Comment by dmentipl** [comment]
For those dealing with this issue, you can do, for example

```bash
GIT_LFS_SKIP_SMUDGE=1 git clone git@github.com:danieljprice/phantom phantom
```

to checkout the repository without the git-lfs quota issue.

**Comment by danieljprice** [comment]
this is very helpful

**Comment by dmentipl** [comment]
The GitHub release is a good idea. I think having data files associated with a particular version is actually a very good side effect. I think doing "micro" releases more frequently would be beneficial to users and developers.

**Comment by dmentipl** [comment]
It might be good to keep this open seeing as it's an ongoing issue, and the workaround is in this thread.

**Comment by dliptai** [comment]
> Probably the right way is to avoid git-lfs altogether. We already have something like this implemented in utils_datafiles.f90 which automatically downloads large files from a website. The problem is that the website is currently my personal one, which is not a good solution, and all the other website hosting services (github.io, bitbucket.io) are basically git repos, which have the same problem with storing old copies of large files.

@danieljprice instead of using your personal website, you could set up a server on a cloud computing service e.g. Nectar.

**Comment by danieljprice** [comment]
@dmentipl poking further into GitHub releases, the issue is that there is no heirarchy in the file system, i.e. we'd need to just store all datafiles individually rather than in the data/subdir/ heirarchy.

@dliptai this would be a nice solution, if Nectar can keep a server running continuously for this. 

One other thing - what we really want is for users to be able to add to the datafile database. This would be hard with Nectar, but no worse than the current solution

**Comment by danieljprice** [comment]
helpful gist on removing git-lfs: https://gist.github.com/everttrollip/198ed9a09bba45d2663ccac99e662201
