### ISSUE TITLE
code configuration for galaxy merger problem

### ISSUE THREAD

**Issue by LayaGhodsi** [danieljprice/phantom#45]
I'm working on a project about using Regression Forest in SPH and I need to reproduce the results of the galaxy merger simulation example in the Phantom paper. I've read the documentation files, but I'm not sure about the right configuration parameters. I wonder if someone can help me with the code configurations to simulate this problem.

**Comment by LayaGhodsi** [comment]
Sorry, I think it's better to send my request via email.

**Comment by danieljprice** [comment]
actually using the tracker is more useful than email. The galaxy merger simulation can be reproduced by compiling the code with SETUP=galaxies:

i.e. ~/phantom/writemake.sh galaxies > Makefile
make setup
./phantomsetup gal
./phantom gal

Feel free to post here if anything does not work for you
