### ISSUE TITLE
Citation requirement in license

### ISSUE THREAD

**Issue by LourensVeen** [danieljprice/phantom#473]
I noticed that you have two additional conditions in your GPLv3 license. The first one is a citation requirement, which is [not a permitted additional condition](https://www.gnu.org/licenses/gpl-faq.en.html#RequireCitation) under 7b. It doesn't fall under 7c either because it doesn't prohibit misrepresentation, it requires representation, and that's a different thing. So by the remainder of section 7, it may be removed by anyone receiving the software. To avoid confusion, it may be better to remove it.

Clearly, citation (including of software!) is important and not citing sources is academic misconduct, but trying to enforce it in the license like this doesn't work. (And imagine every author of a package on your computer adding a term like this. You'd have to cite your kernel and your C library and your window manager and your word processor and your compiler and ...)

Have you considered [archiving your releases on Zenodo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)? That will give them a DOI that people can cite in their papers.

**Comment by danieljprice** [comment]
thanks, happy to remove the citation clause as a requirement of the license if it's not the right way to do it. I also like the Zenodo suggestion, although the annual releases are mainly to remind people that their code is out of date... we try to operate on a continuous integration model where every successful pull request to master [vetted thoroughly by the test suite] is a "release"

**Comment by LourensVeen** [comment]
That sounds like the perfect setup for a CD pipeline actually :smile:. I'm doing the same thing for my software, although I have a separate develop branch which things get merged into, and then merging that into the main branch is part of the release process (I'm using [git flow](https://nvie.com/posts/a-successful-git-branching-model/)). That's infrequent enough that I still haven't got around to setting up a CD workflow, but one day...
