### ISSUE TITLE
Interactivity in phantomsetup

### ISSUE THREAD

**Issue by jameswurster** [danieljprice/phantom#51]
In many of the setup routines, phantomsetup exits after asking the interactive questions.   This is to ensure that the setups are written in such a way that the .in and .setup files can be passed to other researchers and the will be able to reproduce the results.  However, there are some setups (e.g. setup_shock or setup_sphereinbox, and possibly others) where the interactive part of the code either asks about values to be written to the .in file, or calls part of the code that defines values for the .in file.    This results in many of the values in .in being the code default values rather than values appropriate for the given setup.  

Therefore, an elegant solution must be determined, and then several of these setup files will need to be modified; I am only aware of setup_shock and setup_sphereinbox, but please add to this list as appropriate.

**Comment by danieljprice** [comment]
for the setup_disc routines, the current solution is that a parameter determining tmax is read from the .setup file (i.e. end time in number of orbits), and written to the .in file as tmax.

**Comment by danieljprice** [comment]
I just merged this, adding tmax and dtmax to the .setup file is fine, but I don't understand why we have things like alpha, alphau, nfulldump added to the .setup files -- why are these necessary?
