### ISSUE TITLE
error in PHANTOM v2024.0.0: Symbol 'cfac'

### ISSUE THREAD

**Issue by martinatoscani** [danieljprice/phantom#516]
While running make , the following errors occur:

A) "Error: Kind 16 not supported for type REAL at (1)" relative to the file ../src/main/tmunu2grid.f90 (line 390 and 426)
B) "Error: Symbol 'cfac' at (1) has no IMPLICIT type" relative to the file ../src/main/tmunu2grid.f90 (line 385 and 421).

This error is independent on the setup tried.
Version of PHANTOM used: v2024.0.0

**Comment by danieljprice** [comment]
what is the compiler version here? Also is it gfortran or ifort? This passes in the test suite so it's probably an issue with using an older version of the compiler. However, we could probably fix the issues also but I would need to know the compiler version to try to reproduce it...
