### ISSUE TITLE
HdivB/B rapidly increasing in colliding flows

### ISSUE THREAD

**Issue by teogeo1996** [danieljprice/phantom#519]
Whilst running simulations including the creation of a shock compressed layer, the value of HdivB/B rockets well above one even after setting hdivbbmax_max=512 as recommended by the code. Changing overcleanfac to account for this essentially makes the code extremely slow. Is there another way to go about this issue?

**Comment by danieljprice** [comment]
not really, at some point you have to pay the cost to get div B lower... the only other thing here is that we use a cleaning speed of sqrt(cs**2 + va**2) so if you're highly super-Alfvenic then a higher cleaning speed (overcleanfac) could help without killing the timestep too much...

**Comment by danieljprice** [comment]
we recently pushed a fix that may fix the problem here, see #537
