### ISSUE TITLE
Choosing the right number of particles in the PHANTOM SPH simulation

### ISSUE THREAD

**Issue by abbasebriastro** [danieljprice/phantom#520]
For a core with constant density (and isothermal case), I wanted to check the rotation rate (magnetic braking effect)
To start with the number of particles 200k, 400k, 600k and ... 1000K, I ran the program (using sphereinbox_setup.f90[)
It turned out as follows (for half period)

Different number of particles showed different effects. But when the number of particles is 1 million, it seems to show less braking effect compared to the 400K particles.

How to choose the best number of particles?
What is the reason for peaks created in np=1000K (green line)?

(This test was only to choose the best number of particles)![omega-typicalb_brho_.jpg](https://github.com/danieljprice/phantom/assets/135692796/0a19d0ca-87ca-435f-9949-88009ae6b911)

**Comment by danieljprice** [comment]
am closing as this is not really a code issue. In general one should perform a resolution study by increasing the particle  number by at least a factor of 8, corresponding to a factor of 2 increase in linear resolution. The "right" answer is when the result is converged, as in does not change between resolutions. Obviously sometimes one cannot afford this, but then it should be stated in the study that the result is not converged.

**Comment by abbasebriastro** [comment]
Thanks for your response
As a new student, I am definitely facing the limitation of proper guide. Is it possible to you link me with an informed person, if he/she agrees, and I can jointly(as a joint scientific cooperation ) get help from him/her in the technical part of simulation on my work?
