### ISSUE TITLE
last version of the code breaks the wind setup when isink_radiation=1

### ISSUE THREAD

**Issue by lsiess** [danieljprice/phantom#538]
After the addition of the 4th order scheme (April 22, hash 282e51), the wind setup does not work anymore when isink_radiation = 1

**Comment by Yrisch** [comment]
Hi,
For now, you can force the code to work with leapfrog (set use_fourthorder to false). It should resolve the issue temporarily. I checked the routine called for sink radiation in the new substep force routine and it needs an update to use the extrapolation method (mandatory for 4th order). The position of gas and sink particles should be slightly shifted following Chin 2007. I will try to do that in the next few days. Which test I can try to validate the new implementation ?

**Comment by lsiess** [comment]
Hi,
An easy test is to run a wind simulation with an old version of Phantom that worked (e.g. 63d8aef) and compare the results with those obtained with the 4th order scheme.
To generate the code :     writemake.sh wind > Makefile
and attached are the .in and .setup files 
[wind_setup.txt](https://github.com/danieljprice/phantom/files/15187150/wind_setup.txt)
[wind_in.txt](https://github.com/danieljprice/phantom/files/15187151/wind_in.txt)

Thanks!

**Comment by Yrisch** [comment]
Thanks ! I'll try to fix that soon !

**Comment by lsiess** [comment]
Hi Yann

If you plot the radial velocity vr = f(r) 
Attached is what I obtain : in red old version in black new one

![image](https://github.com/danieljprice/phantom/assets/21124753/493729f4-8b82-4128-85c3-6d3654990029)

**Comment by lsiess** [comment]
No, isink_radiation should only adds the radiation pressure force : kappa L/(4 pi r^2 c)

**Comment by danieljprice** [comment]
yes but there is the e^(-tau) term used in some cases

**Comment by lsiess** [comment]
tau should only be needed in Mat's ray tracing, i.e. if iray_resolution /= -1

**Comment by Yrisch** [comment]
the issue comes from the radiation pressure force that is not accounted during the middle force (using extrapolation) with FSI... I forgot to make a patch for this part of the code. I'm working on it.

**Comment by Yrisch** [comment]
Ok I made a patch, but I had to merge get_rad_accel_radiation routine with my main gas force loop. was there a specific reason that the two force was calculated separately in the previous code ?

**Comment by Yrisch** [comment]
Should be fixed with #539

**Comment by danieljprice** [comment]
see comment on #539, it would  be much nicer for this to stay inside the get_force routine if possible. Do we understand why there is a difference between calling it there and separately in the step routine?

**Comment by Yrisch** [comment]
I probably explained my patch badly... The radiation pressure forces are still computed inside the get_force routine. Before that, it was calculated outside the gas force loop (but still inside get_force). Now these radiation forces are computed inside gas loop of the get_force routine. I didn't understand why it wasn't in the previous version of the code (before FSI)...
