### ISSUE TITLE
Reorganize OpenMP statements inside substep routine...

### ISSUE THREAD

**Issue by Yrisch** [danieljprice/phantom#602]
The `substep` routine calls multiple times `kick`, `drift` and `get_force` routines where OpenMP do statements basically point on the same variables.  It could potentially hit  performance of the whole routine by creating and deleting omp workers at each do loop start. One way to fix that could be to open a parallel section at the beginning of `substep` loading everything in memory and put some barrier and master statements to deal with synchronization and serial codes. However, I'm not sure if the compiler can to that under the carpet which will result in no gain in performance with the patch... Does someone have an opinion on this?

**Comment by danieljprice** [comment]
We did do something like this in the radiation_implicit routine, it’s definitely worth trying. With all optimisation the golden rule is “no optimisation without evidence”, ie must ensure it does ACTUALLY run faster with the proposed optimisation than without (you can hope but don’t just assume that it will go faster until it’s tested)

**Comment by Yrisch** [comment]
OK thank you for the advise. I'll then properly test it on simple setups. If it appears to be efficient, I'll open a pull request !

**Comment by Yrisch** [comment]
My first tests do not show any major performance gain. Maybe a few percent but nothing more. This adds a lot of stuff inside these routines, making them unclear... It's also a mess with the omp reduction and the implicit shared/private omp declaration inside the subroutines of the main parallel region. We are forced to put omp barriers everywhere to ensure good synchronization which will further impact performance... This does not seem worth investigating further, at least for the moment. We can close the issue!
