### ISSUE TITLE
New error in grtde with relax=T after commit eda6c81

### ISSUE THREAD

**Issue by maguilarf** [danieljprice/phantom#604]
Hello,

I encountered an issue while running grtde when "relax=T" using a MESA profile for a simple test setup. This setup worked without errors at least up to commit eda6c81. Here are the relevant configuration details:

# options for star
            iprofile =           5    ! 0=Sink,1=Unif,2=Poly,3=Dens,4=KEPL,5=MESA,6=Pie
       input_profile =  profile_ZAMS_1Msun.data   ! Path to input profile
           isoftcore =           0    ! 0=no core softening, 1=cubic, 2=const. entropy
           isinkcore =           F    ! Add a sink particle stellar core
               lcore =       0.000    ! Luminosity of sink core particle [Lsun]
                  np =         300    ! number of particles
               relax =           T    ! relax star into hydrostatic equilibrium
            tol_ekin =   1.000E-07    ! tolerance on ekin/epot to stop relaxation
              maxits =        5000    ! maximum number of relaxation iterations

# options for black hole and orbit
               mhole =   1.000E+06    ! mass of black hole (solar mass)
                beta =       1.000    ! penetration factor
                 ecc =       1.000    ! eccentricity (1 for parabolic)
             norbits =       5.000    ! number of orbits
       dumpsperorbit =         100    ! number of dumps per orbit
               theta =       0.000    ! inclination of orbit (degrees)

However, using the latest commit, this same configuration produces the following error:

ERROR! relax_star: cannot relax star because it is unbound (etherm > epot)

I suspect this issue may be related to changes in the relaxation procedure introduced in the _apr_ commits.

**Comment by danieljprice** [comment]
thanks for flagging this, as you say it should work

**Comment by danieljprice** [comment]
I think I found the problem here, there was a bug with a divide by mstar in the get_mass_coord routine; so the relaxation worked when mstar=1 in code units, but not in the case where mstar /= 1. Will be fixed on #600
