### ISSUE TITLE
Potential energy is not correctly calculated when sink-gas or sink-sink softening is used

### ISSUE THREAD

**Issue by miguelglezb** [danieljprice/phantom#62]
Potential energy is not corrected calculated, which may due to the way the code is calculating the sink particle potential for gas particles inside softening length.

**Comment by danieljprice** [comment]
I think this issue is related to the self-contribution to the potential energy when softening between sink particles is used. So would mainly occur when two sink particles come within each others softening length

**Comment by danieljprice** [comment]
@miguelglezb I believe the commits above should fix the issue - can you please check this from your end?

**Comment by miguelglezb** [comment]
Yes, I'll do a quick test and let you know.

**Comment by danieljprice** [comment]
I found no bugs here so am closing this issue, please re-open it if the problem is still there
