### ISSUE TITLE
Phantom2hdf5: tstop and deltavxyz are not read properly from the original dump

### ISSUE THREAD

**Issue by eragusa** [danieljprice/phantom#70]
I am having some problems with phantom2hdf5.
The new HDF5 dump produced using phantom2hdf5 does not seem to read neither tstop nor deltav for one fluid simulations. The arrays are there, so that in the hdf5 dump both “dump[‘particles’]’[’tstop’]” and “dump[‘particles’][‘deltavxyz’]”  can be accessed but both arrays are entirely initialised to 0 (they also have correct dimensions). Splash can read them properly from the dump, so it looks like a problem only when reading and creating the hdf5 dump.
I tried to dig a bit to try to fix it by my self but I did not manage to do so.
I think that the problem is that when running phantom2hdf5, the code does not read tstop and deltav from the dump, so they remain initialiased to 0, but then they are effectively written in the .h5 dump.
I noted that in the subroutine read_phantom_arrays, no explicit command to load tstop or deltav seems to be there (while write_fulldump_fortran explicitly writes them). I tried adding
call read_array(tstop(ndustfraci,:),tstop_label(ndustfraci),got_tstop(ndustfraci),&
                           ik,i1,i2,noffset,idisk1,tag,match,ierr)
after line 1197 of readwrite_dumps_fortran.F90, where “dustfrac” is read (after adding declaration of the variable got_tstop and updating the “use” statements with tstop, tstop_label etc.).
The compiler does not complain and the phantom2hdf5 works properly but there is no effect on the reading of tstop which remains =0.
Is the command I used wrong?
I am not entirely familiar with read_write dump routines, I would definitely appreciate some guidance from someone more familiar with them.
Thanks!

**Comment by danieljprice** [comment]
Hi @eragusa, unfortunately phantom2hdf5 needs a rewrite (see also #46). At the moment it relies on the phantom read_dump routine which (by definition) only reads information necessary for phantom to continue a calculation. There are no plans to change this.

What is needed is a more or less "direct" read of *everything* present in a dump file, agnostic of how it was written, which is what the splash reader does. The workaround solution is to use Josh's pysplash utility to do the conversion, since this uses the splash reader which will read everything in the file.

Probably we could just delete phantom2hdf5 as a utility in favour of the pysplash solution?

**Comment by eragusa** [comment]
Hi @danieljprice, 
Yes sure, replacing phantom2hdf5 with pysplash sounds as a good solution. I was simply not aware that Josh had created such a tool. Is it already somewhere in the splash/phantom repository or should I ask directly to him?
Cheers

**Comment by eragusa** [comment]
Hi @danieljprice, 
Yes sure, replacing phantom2hdf5 with pysplash sounds as a good solution. I was simply not aware that Josh had created such a tool. Is it already somewhere in the splash/phantom repository or should I ask directly to him?
Cheers

**Comment by eragusa** [comment]
Hi @danieljprice, 
Yes sure, replacing phantom2hdf5 with pysplash sounds as a good solution. I was simply not aware that Josh had created such a tool. Is it already somewhere in the splash/phantom repository or should I ask directly to him?
Cheers

**Comment by danieljprice** [comment]
https://github.com/joshcalcino/PySplashSPH
