### ISSUE TITLE
ulimit -s unlimited does not work on Mac

### ISSUE THREAD

**Issue by DionDonne** [danieljprice/phantom#72]
Hi!

I'm new to phantom and when running the testsuite, the "sink particle/point mass" module fails due to a segmentation error. This was not as expected since the documentation of phantom explains that the following variables should be defined in the bash/zhs-profile in order to prevent this error:

```
export OMP_SCHEDULE="dynamic"
export OMP_STACKSIZE=512M
ulimit -s unlimited
```
More specifically, we get the following error:

```
--> testing sink particle creation (sin)
 >>>>>>  s  t  r  e   t    c     h       m     a    p   p  i  n  g  <<<<<<
 stretching to match density profile in r direction
 density at r =    0.0000000000000000       is    1.0000000000000000     
 total mass      =    6.9604063530626938E-004

Program received signal SIGBUS: Access to an undefined portion of a memory object.

Backtrace for this error:

Program received signal SIGBUS: Access to an undefined portion of a memory object.

Backtrace for this error:
zsh: segmentation fault  ./bin/phantomtest ptmass
```
After doing some research, it has been found that ulimit -s unlimited does not work on Mac: Apple has set a hardlimit on the stacksize (= 65532) and until now we don't know how to circumvent this limit. 

For example, we have tried to use the launchctl command to raise the stack size but to no avail sadly, not even in serverperfmode. We were, therefore, wondering whether a solution exists to this problem or a workaround at least. I'm not an expert in IT so I hope that I have given enough information for the problem to be clarified. Thanks in advance!

Cheers,
Dion

**Comment by jameswurster** [comment]
The hard ulimit on Mac's can be annoying.  I assume most people (including myself) use smaller particle counts locally for testing and developing, and then use HPC machines (with ulimit -s unlimited) to perform the simulations with the desired particle count.  I have successfully run the testsuite on my Mac using ulimit -s 64000

Cheers

**Comment by DionDonne** [comment]
Thanks for the answer. How can I decrease the particle count for the testsuites then?  I'm on the MacBook Air so I guess that my laptop is less powerful than yours as the testsuite has failed again.

Cheers,
Dion

**Comment by jameswurster** [comment]
I remember seeing an issue like this in the tracker, but I can't seem to find it again.  If I recall correctly, there is an issue with the recent version of gfortran that results in the crash.  Slightly older versions (I am using GNU Fortran (Homebrew GCC 9.3.0_1) 9.3.0) seems to work fine.
