### ISSUE TITLE
evrard collapse stretch mapping fails to converge 

### ISSUE THREAD

**Issue by danieljprice** [danieljprice/phantom#90]
In SETUP=star with phantom setup, want a reasonable stellar profile out of setup_star even if relax_star is set to false, but currently we are using random-symmetric particle distribution by default.

This affects e.g. the evrard collapse calculation where there is no real need to "relax" the star, but with the random distribution the initial density profile is very noisy

**Comment by spencermagnall** [comment]
Stretch mapping doesn't converge and produces garbage
Setup file below: 
# Phantom v1.4.0 (c) 2007-2020 The Authors
# input file for Phantom star setup
            iprofile =           7    ! 1=Unif,2=Poly,3=Dens,4=KEPL,5=MESA,6=Piec, 7=Evra

# units
           mass_unit =      solarm    ! mass unit (e.g. solarm)
           dist_unit =      solarr    ! distance unit (e.g. au)

# resolution
                  np =        1000    ! approx number of particles (in box of size 2R)
          use_exactN =           T    ! find closest particle number to np

# equation of state
                ieos =           2    ! 1=isothermal,2=adiabatic,10=MESA,12=idealplusrad
               gamma =  1.66666667    ! Adiabatic index
             ui_coef =       0.050    ! specific internal energy (units of GM/R)

# star properties
               Rstar =       1.000    ! radius of star
               Mstar =       1.000    ! mass of star

# relaxation options
          relax_star =           F    ! relax star automatically during setup
   write_rho_to_file =           F    ! write density profile to file
